# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T00:45:50+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class GoogleAnalyticsAdminV1betaAccessDateRange(BaseModel):
    endDate: Optional[str] = Field(
        None,
        description="The inclusive end date for the query in the format `YYYY-MM-DD`. Cannot be before `startDate`. The format `NdaysAgo`, `yesterday`, or `today` is also accepted, and in that case, the date is inferred based on the current time in the request's time zone.",
    )
    startDate: Optional[str] = Field(
        None,
        description="The inclusive start date for the query in the format `YYYY-MM-DD`. Cannot be after `endDate`. The format `NdaysAgo`, `yesterday`, or `today` is also accepted, and in that case, the date is inferred based on the current time in the request's time zone.",
    )


class GoogleAnalyticsAdminV1betaAccessDimension(BaseModel):
    dimensionName: Optional[str] = Field(
        None,
        description='The API name of the dimension. See [Data Access Schema](https://developers.google.com/analytics/devguides/config/admin/v1/access-api-schema) for the list of dimensions supported in this API. Dimensions are referenced by name in `dimensionFilter` and `orderBys`.',
    )


class GoogleAnalyticsAdminV1betaAccessDimensionHeader(BaseModel):
    dimensionName: Optional[str] = Field(
        None, description="The dimension's name; for example 'userEmail'."
    )


class GoogleAnalyticsAdminV1betaAccessDimensionValue(BaseModel):
    value: Optional[str] = Field(
        None,
        description="The dimension value. For example, this value may be 'France' for the 'country' dimension.",
    )


class GoogleAnalyticsAdminV1betaAccessInListFilter(BaseModel):
    caseSensitive: Optional[bool] = Field(
        None, description='If true, the string value is case sensitive.'
    )
    values: Optional[List[str]] = Field(
        None, description='The list of string values. Must be non-empty.'
    )


class GoogleAnalyticsAdminV1betaAccessMetric(BaseModel):
    metricName: Optional[str] = Field(
        None,
        description='The API name of the metric. See [Data Access Schema](https://developers.google.com/analytics/devguides/config/admin/v1/access-api-schema) for the list of metrics supported in this API. Metrics are referenced by name in `metricFilter` & `orderBys`.',
    )


class GoogleAnalyticsAdminV1betaAccessMetricHeader(BaseModel):
    metricName: Optional[str] = Field(
        None, description="The metric's name; for example 'accessCount'."
    )


class GoogleAnalyticsAdminV1betaAccessMetricValue(BaseModel):
    value: Optional[str] = Field(
        None, description="The measurement value. For example, this value may be '13'."
    )


class Operation(Enum):
    OPERATION_UNSPECIFIED = 'OPERATION_UNSPECIFIED'
    EQUAL = 'EQUAL'
    LESS_THAN = 'LESS_THAN'
    LESS_THAN_OR_EQUAL = 'LESS_THAN_OR_EQUAL'
    GREATER_THAN = 'GREATER_THAN'
    GREATER_THAN_OR_EQUAL = 'GREATER_THAN_OR_EQUAL'


class OrderType(Enum):
    ORDER_TYPE_UNSPECIFIED = 'ORDER_TYPE_UNSPECIFIED'
    ALPHANUMERIC = 'ALPHANUMERIC'
    CASE_INSENSITIVE_ALPHANUMERIC = 'CASE_INSENSITIVE_ALPHANUMERIC'
    NUMERIC = 'NUMERIC'


class GoogleAnalyticsAdminV1betaAccessOrderByDimensionOrderBy(BaseModel):
    dimensionName: Optional[str] = Field(
        None, description='A dimension name in the request to order by.'
    )
    orderType: Optional[OrderType] = Field(
        None, description='Controls the rule for dimension value ordering.'
    )


class GoogleAnalyticsAdminV1betaAccessOrderByMetricOrderBy(BaseModel):
    metricName: Optional[str] = Field(
        None, description='A metric name in the request to order by.'
    )


class GoogleAnalyticsAdminV1betaAccessQuotaStatus(BaseModel):
    consumed: Optional[int] = Field(None, description='Quota consumed by this request.')
    remaining: Optional[int] = Field(
        None, description='Quota remaining after this request.'
    )


class GoogleAnalyticsAdminV1betaAccessRow(BaseModel):
    dimensionValues: Optional[List[GoogleAnalyticsAdminV1betaAccessDimensionValue]] = (
        Field(
            None,
            description='List of dimension values. These values are in the same order as specified in the request.',
        )
    )
    metricValues: Optional[List[GoogleAnalyticsAdminV1betaAccessMetricValue]] = Field(
        None,
        description='List of metric values. These values are in the same order as specified in the request.',
    )


class MatchType(Enum):
    MATCH_TYPE_UNSPECIFIED = 'MATCH_TYPE_UNSPECIFIED'
    EXACT = 'EXACT'
    BEGINS_WITH = 'BEGINS_WITH'
    ENDS_WITH = 'ENDS_WITH'
    CONTAINS = 'CONTAINS'
    FULL_REGEXP = 'FULL_REGEXP'
    PARTIAL_REGEXP = 'PARTIAL_REGEXP'


class GoogleAnalyticsAdminV1betaAccessStringFilter(BaseModel):
    caseSensitive: Optional[bool] = Field(
        None, description='If true, the string value is case sensitive.'
    )
    matchType: Optional[MatchType] = Field(
        None, description='The match type for this filter.'
    )
    value: Optional[str] = Field(
        None, description='The string value used for the matching.'
    )


class GoogleAnalyticsAdminV1betaAccount(BaseModel):
    createTime: Optional[str] = Field(
        None, description='Output only. Time when this account was originally created.'
    )
    deleted: Optional[bool] = Field(
        None,
        description='Output only. Indicates whether this Account is soft-deleted or not. Deleted accounts are excluded from List results unless specifically requested.',
    )
    displayName: Optional[str] = Field(
        None, description='Required. Human-readable display name for this account.'
    )
    name: Optional[str] = Field(
        None,
        description='Output only. Resource name of this account. Format: accounts/{account} Example: "accounts/100"',
    )
    regionCode: Optional[str] = Field(
        None, description='Country of business. Must be a Unicode CLDR region code.'
    )
    updateTime: Optional[str] = Field(
        None,
        description='Output only. Time when account payload fields were last updated.',
    )


class GoogleAnalyticsAdminV1betaAcknowledgeUserDataCollectionRequest(BaseModel):
    acknowledgement: Optional[str] = Field(
        None,
        description='Required. An acknowledgement that the caller of this method understands the terms of user data collection. This field must contain the exact value: "I acknowledge that I have the necessary privacy disclosures and rights from my end users for the collection and processing of their data, including the association of such data with the visitation information Google Analytics collects from my site and/or app property."',
    )


class GoogleAnalyticsAdminV1betaAcknowledgeUserDataCollectionResponse(BaseModel):
    pass


class GoogleAnalyticsAdminV1betaArchiveCustomDimensionRequest(BaseModel):
    pass


class GoogleAnalyticsAdminV1betaArchiveCustomMetricRequest(BaseModel):
    pass


class Action(Enum):
    ACTION_TYPE_UNSPECIFIED = 'ACTION_TYPE_UNSPECIFIED'
    CREATED = 'CREATED'
    UPDATED = 'UPDATED'
    DELETED = 'DELETED'


class ActorType(Enum):
    ACTOR_TYPE_UNSPECIFIED = 'ACTOR_TYPE_UNSPECIFIED'
    USER = 'USER'
    SYSTEM = 'SYSTEM'
    SUPPORT = 'SUPPORT'


class GoogleAnalyticsAdminV1betaConversionEvent(BaseModel):
    createTime: Optional[str] = Field(
        None,
        description='Output only. Time when this conversion event was created in the property.',
    )
    custom: Optional[bool] = Field(
        None,
        description='Output only. If set to true, this conversion event refers to a custom event. If set to false, this conversion event refers to a default event in GA. Default events typically have special meaning in GA. Default events are usually created for you by the GA system, but in some cases can be created by property admins. Custom events count towards the maximum number of custom conversion events that may be created per property.',
    )
    deletable: Optional[bool] = Field(
        None,
        description='Output only. If set, this event can currently be deleted with DeleteConversionEvent.',
    )
    eventName: Optional[str] = Field(
        None,
        description="Immutable. The event name for this conversion event. Examples: 'click', 'purchase'",
    )
    name: Optional[str] = Field(
        None,
        description='Output only. Resource name of this conversion event. Format: properties/{property}/conversionEvents/{conversion_event}',
    )


class Scope(Enum):
    DIMENSION_SCOPE_UNSPECIFIED = 'DIMENSION_SCOPE_UNSPECIFIED'
    EVENT = 'EVENT'
    USER = 'USER'
    ITEM = 'ITEM'


class GoogleAnalyticsAdminV1betaCustomDimension(BaseModel):
    description: Optional[str] = Field(
        None,
        description='Optional. Description for this custom dimension. Max length of 150 characters.',
    )
    disallowAdsPersonalization: Optional[bool] = Field(
        None,
        description='Optional. If set to true, sets this dimension as NPA and excludes it from ads personalization. This is currently only supported by user-scoped custom dimensions.',
    )
    displayName: Optional[str] = Field(
        None,
        description='Required. Display name for this custom dimension as shown in the Analytics UI. Max length of 82 characters, alphanumeric plus space and underscore starting with a letter. Legacy system-generated display names may contain square brackets, but updates to this field will never permit square brackets.',
    )
    name: Optional[str] = Field(
        None,
        description='Output only. Resource name for this CustomDimension resource. Format: properties/{property}/customDimensions/{customDimension}',
    )
    parameterName: Optional[str] = Field(
        None,
        description='Required. Immutable. Tagging parameter name for this custom dimension. If this is a user-scoped dimension, then this is the user property name. If this is an event-scoped dimension, then this is the event parameter name. If this is an item-scoped dimension, then this is the parameter name found in the eCommerce items array. May only contain alphanumeric and underscore characters, starting with a letter. Max length of 24 characters for user-scoped dimensions, 40 characters for event-scoped dimensions.',
    )
    scope: Optional[Scope] = Field(
        None, description='Required. Immutable. The scope of this dimension.'
    )


class MeasurementUnit(Enum):
    MEASUREMENT_UNIT_UNSPECIFIED = 'MEASUREMENT_UNIT_UNSPECIFIED'
    STANDARD = 'STANDARD'
    CURRENCY = 'CURRENCY'
    FEET = 'FEET'
    METERS = 'METERS'
    KILOMETERS = 'KILOMETERS'
    MILES = 'MILES'
    MILLISECONDS = 'MILLISECONDS'
    SECONDS = 'SECONDS'
    MINUTES = 'MINUTES'
    HOURS = 'HOURS'


class RestrictedMetricTypeEnum(Enum):
    RESTRICTED_METRIC_TYPE_UNSPECIFIED = 'RESTRICTED_METRIC_TYPE_UNSPECIFIED'
    COST_DATA = 'COST_DATA'
    REVENUE_DATA = 'REVENUE_DATA'


class Scope1(Enum):
    METRIC_SCOPE_UNSPECIFIED = 'METRIC_SCOPE_UNSPECIFIED'
    EVENT = 'EVENT'


class GoogleAnalyticsAdminV1betaCustomMetric(BaseModel):
    description: Optional[str] = Field(
        None,
        description='Optional. Description for this custom dimension. Max length of 150 characters.',
    )
    displayName: Optional[str] = Field(
        None,
        description='Required. Display name for this custom metric as shown in the Analytics UI. Max length of 82 characters, alphanumeric plus space and underscore starting with a letter. Legacy system-generated display names may contain square brackets, but updates to this field will never permit square brackets.',
    )
    measurementUnit: Optional[MeasurementUnit] = Field(
        None, description="Required. The type for the custom metric's value."
    )
    name: Optional[str] = Field(
        None,
        description='Output only. Resource name for this CustomMetric resource. Format: properties/{property}/customMetrics/{customMetric}',
    )
    parameterName: Optional[str] = Field(
        None,
        description='Required. Immutable. Tagging name for this custom metric. If this is an event-scoped metric, then this is the event parameter name. May only contain alphanumeric and underscore charactes, starting with a letter. Max length of 40 characters for event-scoped metrics.',
    )
    restrictedMetricType: Optional[List[RestrictedMetricTypeEnum]] = Field(
        None,
        description='Optional. Types of restricted data that this metric may contain. Required for metrics with CURRENCY measurement unit. Must be empty for metrics with a non-CURRENCY measurement unit.',
    )
    scope: Optional[Scope1] = Field(
        None, description='Required. Immutable. The scope of this custom metric.'
    )


class EventDataRetention(Enum):
    RETENTION_DURATION_UNSPECIFIED = 'RETENTION_DURATION_UNSPECIFIED'
    TWO_MONTHS = 'TWO_MONTHS'
    FOURTEEN_MONTHS = 'FOURTEEN_MONTHS'
    TWENTY_SIX_MONTHS = 'TWENTY_SIX_MONTHS'
    THIRTY_EIGHT_MONTHS = 'THIRTY_EIGHT_MONTHS'
    FIFTY_MONTHS = 'FIFTY_MONTHS'


class GoogleAnalyticsAdminV1betaDataRetentionSettings(BaseModel):
    eventDataRetention: Optional[EventDataRetention] = Field(
        None, description='The length of time that event-level data is retained.'
    )
    name: Optional[str] = Field(
        None,
        description='Output only. Resource name for this DataRetentionSetting resource. Format: properties/{property}/dataRetentionSettings',
    )
    resetUserDataOnNewActivity: Optional[bool] = Field(
        None,
        description='If true, reset the retention period for the user identifier with every event from that user.',
    )


class GoogleAnalyticsAdminV1betaDataSharingSettings(BaseModel):
    name: Optional[str] = Field(
        None,
        description='Output only. Resource name. Format: accounts/{account}/dataSharingSettings Example: "accounts/1000/dataSharingSettings"',
    )
    sharingWithGoogleAnySalesEnabled: Optional[bool] = Field(
        None,
        description='Allows any of Google sales to access the data in order to suggest configuration changes to improve results.',
    )
    sharingWithGoogleAssignedSalesEnabled: Optional[bool] = Field(
        None,
        description='Allows Google sales teams that are assigned to the customer to access the data in order to suggest configuration changes to improve results. Sales team restrictions still apply when enabled.',
    )
    sharingWithGoogleProductsEnabled: Optional[bool] = Field(
        None,
        description='Allows Google to use the data to improve other Google products or services.',
    )
    sharingWithGoogleSupportEnabled: Optional[bool] = Field(
        None,
        description='Allows Google support to access the data in order to help troubleshoot issues.',
    )
    sharingWithOthersEnabled: Optional[bool] = Field(
        None,
        description='Allows Google to share the data anonymously in aggregate form with others.',
    )


class Type(Enum):
    DATA_STREAM_TYPE_UNSPECIFIED = 'DATA_STREAM_TYPE_UNSPECIFIED'
    WEB_DATA_STREAM = 'WEB_DATA_STREAM'
    ANDROID_APP_DATA_STREAM = 'ANDROID_APP_DATA_STREAM'
    IOS_APP_DATA_STREAM = 'IOS_APP_DATA_STREAM'


class GoogleAnalyticsAdminV1betaDataStreamAndroidAppStreamData(BaseModel):
    firebaseAppId: Optional[str] = Field(
        None,
        description='Output only. ID of the corresponding Android app in Firebase, if any. This ID can change if the Android app is deleted and recreated.',
    )
    packageName: Optional[str] = Field(
        None,
        description='Immutable. The package name for the app being measured. Example: "com.example.myandroidapp"',
    )


class GoogleAnalyticsAdminV1betaDataStreamIosAppStreamData(BaseModel):
    bundleId: Optional[str] = Field(
        None,
        description='Required. Immutable. The Apple App Store Bundle ID for the app Example: "com.example.myiosapp"',
    )
    firebaseAppId: Optional[str] = Field(
        None,
        description='Output only. ID of the corresponding iOS app in Firebase, if any. This ID can change if the iOS app is deleted and recreated.',
    )


class GoogleAnalyticsAdminV1betaDataStreamWebStreamData(BaseModel):
    defaultUri: Optional[str] = Field(
        None,
        description='Immutable. Domain name of the web app being measured, or empty. Example: "http://www.google.com", "https://www.google.com"',
    )
    firebaseAppId: Optional[str] = Field(
        None,
        description='Output only. ID of the corresponding web app in Firebase, if any. This ID can change if the web app is deleted and recreated.',
    )
    measurementId: Optional[str] = Field(
        None,
        description='Output only. Analytics "Measurement ID", without the "G-" prefix. Example: "G-1A2BCD345E" would just be "1A2BCD345E"',
    )


class GoogleAnalyticsAdminV1betaFirebaseLink(BaseModel):
    createTime: Optional[str] = Field(
        None,
        description='Output only. Time when this FirebaseLink was originally created.',
    )
    name: Optional[str] = Field(
        None,
        description='Output only. Example format: properties/1234/firebaseLinks/5678',
    )
    project: Optional[str] = Field(
        None,
        description="Immutable. Firebase project resource name. When creating a FirebaseLink, you may provide this resource name using either a project number or project ID. Once this resource has been created, returned FirebaseLinks will always have a project_name that contains a project number. Format: 'projects/{project number}' Example: 'projects/1234'",
    )


class GoogleAnalyticsAdminV1betaGoogleAdsLink(BaseModel):
    adsPersonalizationEnabled: Optional[bool] = Field(
        None,
        description='Enable personalized advertising features with this integration. Automatically publish my Google Analytics audience lists and Google Analytics remarketing events/parameters to the linked Google Ads account. If this field is not set on create/update, it will be defaulted to true.',
    )
    canManageClients: Optional[bool] = Field(
        None,
        description='Output only. If true, this link is for a Google Ads manager account.',
    )
    createTime: Optional[str] = Field(
        None, description='Output only. Time when this link was originally created.'
    )
    creatorEmailAddress: Optional[str] = Field(
        None,
        description="Output only. Email address of the user that created the link. An empty string will be returned if the email address can't be retrieved.",
    )
    customerId: Optional[str] = Field(
        None, description='Immutable. Google Ads customer ID.'
    )
    name: Optional[str] = Field(
        None,
        description='Output only. Format: properties/{propertyId}/googleAdsLinks/{googleAdsLinkId} Note: googleAdsLinkId is not the Google Ads customer ID.',
    )
    updateTime: Optional[str] = Field(
        None, description='Output only. Time when this link was last updated.'
    )


class GoogleAnalyticsAdminV1betaListAccountsResponse(BaseModel):
    accounts: Optional[List[GoogleAnalyticsAdminV1betaAccount]] = Field(
        None, description='Results that were accessible to the caller.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.',
    )


class GoogleAnalyticsAdminV1betaListConversionEventsResponse(BaseModel):
    conversionEvents: Optional[List[GoogleAnalyticsAdminV1betaConversionEvent]] = Field(
        None, description='The requested conversion events'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.',
    )


class GoogleAnalyticsAdminV1betaListCustomDimensionsResponse(BaseModel):
    customDimensions: Optional[List[GoogleAnalyticsAdminV1betaCustomDimension]] = Field(
        None, description='List of CustomDimensions.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.',
    )


class GoogleAnalyticsAdminV1betaListCustomMetricsResponse(BaseModel):
    customMetrics: Optional[List[GoogleAnalyticsAdminV1betaCustomMetric]] = Field(
        None, description='List of CustomMetrics.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.',
    )


class GoogleAnalyticsAdminV1betaListFirebaseLinksResponse(BaseModel):
    firebaseLinks: Optional[List[GoogleAnalyticsAdminV1betaFirebaseLink]] = Field(
        None, description='List of FirebaseLinks. This will have at most one value.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages. Currently, Google Analytics supports only one FirebaseLink per property, so this will never be populated.',
    )


class GoogleAnalyticsAdminV1betaListGoogleAdsLinksResponse(BaseModel):
    googleAdsLinks: Optional[List[GoogleAnalyticsAdminV1betaGoogleAdsLink]] = Field(
        None, description='List of GoogleAdsLinks.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.',
    )


class GoogleAnalyticsAdminV1betaMeasurementProtocolSecret(BaseModel):
    displayName: Optional[str] = Field(
        None, description='Required. Human-readable display name for this secret.'
    )
    name: Optional[str] = Field(
        None,
        description='Output only. Resource name of this secret. This secret may be a child of any type of stream. Format: properties/{property}/dataStreams/{dataStream}/measurementProtocolSecrets/{measurementProtocolSecret}',
    )
    secretValue: Optional[str] = Field(
        None,
        description="Output only. The measurement protocol secret value. Pass this value to the api_secret field of the Measurement Protocol API when sending hits to this secret's parent property.",
    )


class GoogleAnalyticsAdminV1betaNumericValue(BaseModel):
    doubleValue: Optional[float] = Field(None, description='Double value')
    int64Value: Optional[str] = Field(None, description='Integer value')


class IndustryCategory(Enum):
    INDUSTRY_CATEGORY_UNSPECIFIED = 'INDUSTRY_CATEGORY_UNSPECIFIED'
    AUTOMOTIVE = 'AUTOMOTIVE'
    BUSINESS_AND_INDUSTRIAL_MARKETS = 'BUSINESS_AND_INDUSTRIAL_MARKETS'
    FINANCE = 'FINANCE'
    HEALTHCARE = 'HEALTHCARE'
    TECHNOLOGY = 'TECHNOLOGY'
    TRAVEL = 'TRAVEL'
    OTHER = 'OTHER'
    ARTS_AND_ENTERTAINMENT = 'ARTS_AND_ENTERTAINMENT'
    BEAUTY_AND_FITNESS = 'BEAUTY_AND_FITNESS'
    BOOKS_AND_LITERATURE = 'BOOKS_AND_LITERATURE'
    FOOD_AND_DRINK = 'FOOD_AND_DRINK'
    GAMES = 'GAMES'
    HOBBIES_AND_LEISURE = 'HOBBIES_AND_LEISURE'
    HOME_AND_GARDEN = 'HOME_AND_GARDEN'
    INTERNET_AND_TELECOM = 'INTERNET_AND_TELECOM'
    LAW_AND_GOVERNMENT = 'LAW_AND_GOVERNMENT'
    NEWS = 'NEWS'
    ONLINE_COMMUNITIES = 'ONLINE_COMMUNITIES'
    PEOPLE_AND_SOCIETY = 'PEOPLE_AND_SOCIETY'
    PETS_AND_ANIMALS = 'PETS_AND_ANIMALS'
    REAL_ESTATE = 'REAL_ESTATE'
    REFERENCE = 'REFERENCE'
    SCIENCE = 'SCIENCE'
    SPORTS = 'SPORTS'
    JOBS_AND_EDUCATION = 'JOBS_AND_EDUCATION'
    SHOPPING = 'SHOPPING'


class PropertyType(Enum):
    PROPERTY_TYPE_UNSPECIFIED = 'PROPERTY_TYPE_UNSPECIFIED'
    PROPERTY_TYPE_ORDINARY = 'PROPERTY_TYPE_ORDINARY'
    PROPERTY_TYPE_SUBPROPERTY = 'PROPERTY_TYPE_SUBPROPERTY'
    PROPERTY_TYPE_ROLLUP = 'PROPERTY_TYPE_ROLLUP'


class ServiceLevel(Enum):
    SERVICE_LEVEL_UNSPECIFIED = 'SERVICE_LEVEL_UNSPECIFIED'
    GOOGLE_ANALYTICS_STANDARD = 'GOOGLE_ANALYTICS_STANDARD'
    GOOGLE_ANALYTICS_360 = 'GOOGLE_ANALYTICS_360'


class GoogleAnalyticsAdminV1betaProperty(BaseModel):
    account: Optional[str] = Field(
        None,
        description='Immutable. The resource name of the parent account Format: accounts/{account_id} Example: "accounts/123"',
    )
    createTime: Optional[str] = Field(
        None, description='Output only. Time when the entity was originally created.'
    )
    currencyCode: Optional[str] = Field(
        None,
        description='The currency type used in reports involving monetary values. Format: https://en.wikipedia.org/wiki/ISO_4217 Examples: "USD", "EUR", "JPY"',
    )
    deleteTime: Optional[str] = Field(
        None,
        description='Output only. If set, the time at which this property was trashed. If not set, then this property is not currently in the trash can.',
    )
    displayName: Optional[str] = Field(
        None,
        description='Required. Human-readable display name for this property. The max allowed display name length is 100 UTF-16 code units.',
    )
    expireTime: Optional[str] = Field(
        None,
        description='Output only. If set, the time at which this trashed property will be permanently deleted. If not set, then this property is not currently in the trash can and is not slated to be deleted.',
    )
    industryCategory: Optional[IndustryCategory] = Field(
        None,
        description='Industry associated with this property Example: AUTOMOTIVE, FOOD_AND_DRINK',
    )
    name: Optional[str] = Field(
        None,
        description='Output only. Resource name of this property. Format: properties/{property_id} Example: "properties/1000"',
    )
    parent: Optional[str] = Field(
        None,
        description='Immutable. Resource name of this property\'s logical parent. Note: The Property-Moving UI can be used to change the parent. Format: accounts/{account}, properties/{property} Example: "accounts/100", "properties/101"',
    )
    propertyType: Optional[PropertyType] = Field(
        None,
        description='Immutable. The property type for this Property resource. When creating a property, if the type is "PROPERTY_TYPE_UNSPECIFIED", then "ORDINARY_PROPERTY" will be implied. "SUBPROPERTY" and "ROLLUP_PROPERTY" types cannot yet be created with the Google Analytics Admin API.',
    )
    serviceLevel: Optional[ServiceLevel] = Field(
        None,
        description='Output only. The Google Analytics service level that applies to this property.',
    )
    timeZone: Optional[str] = Field(
        None,
        description='Required. Reporting Time Zone, used as the day boundary for reports, regardless of where the data originates. If the time zone honors DST, Analytics will automatically adjust for the changes. NOTE: Changing the time zone only affects data going forward, and is not applied retroactively. Format: https://www.iana.org/time-zones Example: "America/Los_Angeles"',
    )
    updateTime: Optional[str] = Field(
        None,
        description='Output only. Time when entity payload fields were last updated.',
    )


class GoogleAnalyticsAdminV1betaPropertySummary(BaseModel):
    displayName: Optional[str] = Field(
        None,
        description='Display name for the property referred to in this property summary.',
    )
    parent: Optional[str] = Field(
        None,
        description='Resource name of this property\'s logical parent. Note: The Property-Moving UI can be used to change the parent. Format: accounts/{account}, properties/{property} Example: "accounts/100", "properties/200"',
    )
    property: Optional[str] = Field(
        None,
        description='Resource name of property referred to by this property summary Format: properties/{property_id} Example: "properties/1000"',
    )
    propertyType: Optional[PropertyType] = Field(
        None, description="The property's property type."
    )


class GoogleAnalyticsAdminV1betaProvisionAccountTicketRequest(BaseModel):
    account: Optional[GoogleAnalyticsAdminV1betaAccount] = Field(
        None, description='The account to create.'
    )
    redirectUri: Optional[str] = Field(
        None,
        description='Redirect URI where the user will be sent after accepting Terms of Service. Must be configured in Cloud Console as a Redirect URI.',
    )


class GoogleAnalyticsAdminV1betaProvisionAccountTicketResponse(BaseModel):
    accountTicketId: Optional[str] = Field(
        None, description='The param to be passed in the ToS link.'
    )


class ActionEnum(Enum):
    ACTION_TYPE_UNSPECIFIED = 'ACTION_TYPE_UNSPECIFIED'
    CREATED = 'CREATED'
    UPDATED = 'UPDATED'
    DELETED = 'DELETED'


class ResourceTypeEnum(Enum):
    CHANGE_HISTORY_RESOURCE_TYPE_UNSPECIFIED = (
        'CHANGE_HISTORY_RESOURCE_TYPE_UNSPECIFIED'
    )
    ACCOUNT = 'ACCOUNT'
    PROPERTY = 'PROPERTY'
    FIREBASE_LINK = 'FIREBASE_LINK'
    GOOGLE_ADS_LINK = 'GOOGLE_ADS_LINK'
    GOOGLE_SIGNALS_SETTINGS = 'GOOGLE_SIGNALS_SETTINGS'
    CONVERSION_EVENT = 'CONVERSION_EVENT'
    MEASUREMENT_PROTOCOL_SECRET = 'MEASUREMENT_PROTOCOL_SECRET'
    DATA_RETENTION_SETTINGS = 'DATA_RETENTION_SETTINGS'
    DISPLAY_VIDEO_360_ADVERTISER_LINK = 'DISPLAY_VIDEO_360_ADVERTISER_LINK'
    DISPLAY_VIDEO_360_ADVERTISER_LINK_PROPOSAL = (
        'DISPLAY_VIDEO_360_ADVERTISER_LINK_PROPOSAL'
    )
    DATA_STREAM = 'DATA_STREAM'
    ATTRIBUTION_SETTINGS = 'ATTRIBUTION_SETTINGS'


class GoogleAnalyticsAdminV1betaSearchChangeHistoryEventsRequest(BaseModel):
    action: Optional[List[ActionEnum]] = Field(
        None,
        description='Optional. If set, only return changes that match one or more of these types of actions.',
    )
    actorEmail: Optional[List[str]] = Field(
        None,
        description='Optional. If set, only return changes if they are made by a user in this list.',
    )
    earliestChangeTime: Optional[str] = Field(
        None,
        description='Optional. If set, only return changes made after this time (inclusive).',
    )
    latestChangeTime: Optional[str] = Field(
        None,
        description='Optional. If set, only return changes made before this time (inclusive).',
    )
    pageSize: Optional[int] = Field(
        None,
        description='Optional. The maximum number of ChangeHistoryEvent items to return. The service may return fewer than this value, even if there are additional pages. If unspecified, at most 50 items will be returned. The maximum value is 200 (higher values will be coerced to the maximum).',
    )
    pageToken: Optional[str] = Field(
        None,
        description='Optional. A page token, received from a previous `SearchChangeHistoryEvents` call. Provide this to retrieve the subsequent page. When paginating, all other parameters provided to `SearchChangeHistoryEvents` must match the call that provided the page token.',
    )
    property: Optional[str] = Field(
        None,
        description='Optional. Resource name for a child property. If set, only return changes made to this property or its child resources.',
    )
    resourceType: Optional[List[ResourceTypeEnum]] = Field(
        None,
        description='Optional. If set, only return changes if they are for a resource that matches at least one of these types.',
    )


class GoogleProtobufEmpty(BaseModel):
    pass


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class GoogleAnalyticsAdminV1betaAccessBetweenFilter(BaseModel):
    fromValue: Optional[GoogleAnalyticsAdminV1betaNumericValue] = Field(
        None, description='Begins with this number.'
    )
    toValue: Optional[GoogleAnalyticsAdminV1betaNumericValue] = Field(
        None, description='Ends with this number.'
    )


class GoogleAnalyticsAdminV1betaAccessNumericFilter(BaseModel):
    operation: Optional[Operation] = Field(
        None, description='The operation type for this filter.'
    )
    value: Optional[GoogleAnalyticsAdminV1betaNumericValue] = Field(
        None, description='A numeric value or a date value.'
    )


class GoogleAnalyticsAdminV1betaAccessOrderBy(BaseModel):
    desc: Optional[bool] = Field(
        None,
        description='If true, sorts by descending order. If false or unspecified, sorts in ascending order.',
    )
    dimension: Optional[GoogleAnalyticsAdminV1betaAccessOrderByDimensionOrderBy] = (
        Field(None, description="Sorts results by a dimension's values.")
    )
    metric: Optional[GoogleAnalyticsAdminV1betaAccessOrderByMetricOrderBy] = Field(
        None, description="Sorts results by a metric's values."
    )


class GoogleAnalyticsAdminV1betaAccessQuota(BaseModel):
    concurrentRequests: Optional[GoogleAnalyticsAdminV1betaAccessQuotaStatus] = Field(
        None, description='Properties can use up to 50 concurrent requests.'
    )
    serverErrorsPerProjectPerHour: Optional[
        GoogleAnalyticsAdminV1betaAccessQuotaStatus
    ] = Field(
        None,
        description='Properties and cloud project pairs can have up to 50 server errors per hour.',
    )
    tokensPerDay: Optional[GoogleAnalyticsAdminV1betaAccessQuotaStatus] = Field(
        None,
        description='Properties can use 250,000 tokens per day. Most requests consume fewer than 10 tokens.',
    )
    tokensPerHour: Optional[GoogleAnalyticsAdminV1betaAccessQuotaStatus] = Field(
        None,
        description='Properties can use 50,000 tokens per hour. An API request consumes a single number of tokens, and that number is deducted from all of the hourly, daily, and per project hourly quotas.',
    )
    tokensPerProjectPerHour: Optional[GoogleAnalyticsAdminV1betaAccessQuotaStatus] = (
        Field(
            None,
            description='Properties can use up to 25% of their tokens per project per hour. This amounts to Analytics 360 Properties can use 12,500 tokens per project per hour. An API request consumes a single number of tokens, and that number is deducted from all of the hourly, daily, and per project hourly quotas.',
        )
    )


class GoogleAnalyticsAdminV1betaAccountSummary(BaseModel):
    account: Optional[str] = Field(
        None,
        description='Resource name of account referred to by this account summary Format: accounts/{account_id} Example: "accounts/1000"',
    )
    displayName: Optional[str] = Field(
        None,
        description='Display name for the account referred to in this account summary.',
    )
    name: Optional[str] = Field(
        None,
        description='Resource name for this account summary. Format: accountSummaries/{account_id} Example: "accountSummaries/1000"',
    )
    propertySummaries: Optional[List[GoogleAnalyticsAdminV1betaPropertySummary]] = (
        Field(None, description='List of summaries for child accounts of this account.')
    )


class GoogleAnalyticsAdminV1betaDataStream(BaseModel):
    androidAppStreamData: Optional[
        GoogleAnalyticsAdminV1betaDataStreamAndroidAppStreamData
    ] = Field(
        None,
        description='Data specific to Android app streams. Must be populated if type is ANDROID_APP_DATA_STREAM.',
    )
    createTime: Optional[str] = Field(
        None, description='Output only. Time when this stream was originally created.'
    )
    displayName: Optional[str] = Field(
        None,
        description='Human-readable display name for the Data Stream. Required for web data streams. The max allowed display name length is 255 UTF-16 code units.',
    )
    iosAppStreamData: Optional[GoogleAnalyticsAdminV1betaDataStreamIosAppStreamData] = (
        Field(
            None,
            description='Data specific to iOS app streams. Must be populated if type is IOS_APP_DATA_STREAM.',
        )
    )
    name: Optional[str] = Field(
        None,
        description='Output only. Resource name of this Data Stream. Format: properties/{property_id}/dataStreams/{stream_id} Example: "properties/1000/dataStreams/2000"',
    )
    type: Optional[Type] = Field(
        None, description='Required. Immutable. The type of this DataStream resource.'
    )
    updateTime: Optional[str] = Field(
        None,
        description='Output only. Time when stream payload fields were last updated.',
    )
    webStreamData: Optional[GoogleAnalyticsAdminV1betaDataStreamWebStreamData] = Field(
        None,
        description='Data specific to web streams. Must be populated if type is WEB_DATA_STREAM.',
    )


class GoogleAnalyticsAdminV1betaListAccountSummariesResponse(BaseModel):
    accountSummaries: Optional[List[GoogleAnalyticsAdminV1betaAccountSummary]] = Field(
        None, description='Account summaries of all accounts the caller has access to.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.',
    )


class GoogleAnalyticsAdminV1betaListDataStreamsResponse(BaseModel):
    dataStreams: Optional[List[GoogleAnalyticsAdminV1betaDataStream]] = Field(
        None, description='List of DataStreams.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.',
    )


class GoogleAnalyticsAdminV1betaListMeasurementProtocolSecretsResponse(BaseModel):
    measurementProtocolSecrets: Optional[
        List[GoogleAnalyticsAdminV1betaMeasurementProtocolSecret]
    ] = Field(
        None,
        description='A list of secrets for the parent stream specified in the request.',
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.',
    )


class GoogleAnalyticsAdminV1betaListPropertiesResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.',
    )
    properties: Optional[List[GoogleAnalyticsAdminV1betaProperty]] = Field(
        None,
        description='Results that matched the filter criteria and were accessible to the caller.',
    )


class GoogleAnalyticsAdminV1betaRunAccessReportResponse(BaseModel):
    dimensionHeaders: Optional[
        List[GoogleAnalyticsAdminV1betaAccessDimensionHeader]
    ] = Field(
        None,
        description='The header for a column in the report that corresponds to a specific dimension. The number of DimensionHeaders and ordering of DimensionHeaders matches the dimensions present in rows.',
    )
    metricHeaders: Optional[List[GoogleAnalyticsAdminV1betaAccessMetricHeader]] = Field(
        None,
        description='The header for a column in the report that corresponds to a specific metric. The number of MetricHeaders and ordering of MetricHeaders matches the metrics present in rows.',
    )
    quota: Optional[GoogleAnalyticsAdminV1betaAccessQuota] = Field(
        None,
        description="The quota state for this Analytics property including this request. This field doesn't work with account-level requests.",
    )
    rowCount: Optional[int] = Field(
        None,
        description='The total number of rows in the query result. `rowCount` is independent of the number of rows returned in the response, the `limit` request parameter, and the `offset` request parameter. For example if a query returns 175 rows and includes `limit` of 50 in the API request, the response will contain `rowCount` of 175 but only 50 rows. To learn more about this pagination parameter, see [Pagination](https://developers.google.com/analytics/devguides/reporting/data/v1/basics#pagination).',
    )
    rows: Optional[List[GoogleAnalyticsAdminV1betaAccessRow]] = Field(
        None,
        description='Rows of dimension value combinations and metric values in the report.',
    )


class GoogleAnalyticsAdminV1betaAccessFilter(BaseModel):
    betweenFilter: Optional[GoogleAnalyticsAdminV1betaAccessBetweenFilter] = Field(
        None, description='A filter for two values.'
    )
    fieldName: Optional[str] = Field(
        None, description='The dimension name or metric name.'
    )
    inListFilter: Optional[GoogleAnalyticsAdminV1betaAccessInListFilter] = Field(
        None, description='A filter for in list values.'
    )
    numericFilter: Optional[GoogleAnalyticsAdminV1betaAccessNumericFilter] = Field(
        None, description='A filter for numeric or date values.'
    )
    stringFilter: Optional[GoogleAnalyticsAdminV1betaAccessStringFilter] = Field(
        None, description='Strings related filter.'
    )


class GoogleAnalyticsAdminV1betaChangeHistoryChangeChangeHistoryResource(BaseModel):
    account: Optional[GoogleAnalyticsAdminV1betaAccount] = Field(
        None, description='A snapshot of an Account resource in change history.'
    )
    conversionEvent: Optional[GoogleAnalyticsAdminV1betaConversionEvent] = Field(
        None, description='A snapshot of a ConversionEvent resource in change history.'
    )
    dataRetentionSettings: Optional[GoogleAnalyticsAdminV1betaDataRetentionSettings] = (
        Field(
            None,
            description='A snapshot of a data retention settings resource in change history.',
        )
    )
    dataStream: Optional[GoogleAnalyticsAdminV1betaDataStream] = Field(
        None, description='A snapshot of a DataStream resource in change history.'
    )
    firebaseLink: Optional[GoogleAnalyticsAdminV1betaFirebaseLink] = Field(
        None, description='A snapshot of a FirebaseLink resource in change history.'
    )
    googleAdsLink: Optional[GoogleAnalyticsAdminV1betaGoogleAdsLink] = Field(
        None, description='A snapshot of a GoogleAdsLink resource in change history.'
    )
    measurementProtocolSecret: Optional[
        GoogleAnalyticsAdminV1betaMeasurementProtocolSecret
    ] = Field(
        None,
        description='A snapshot of a MeasurementProtocolSecret resource in change history.',
    )
    property: Optional[GoogleAnalyticsAdminV1betaProperty] = Field(
        None, description='A snapshot of a Property resource in change history.'
    )


class GoogleAnalyticsAdminV1betaChangeHistoryChange(BaseModel):
    action: Optional[Action] = Field(
        None, description='The type of action that changed this resource.'
    )
    resource: Optional[str] = Field(
        None,
        description='Resource name of the resource whose changes are described by this entry.',
    )
    resourceAfterChange: Optional[
        GoogleAnalyticsAdminV1betaChangeHistoryChangeChangeHistoryResource
    ] = Field(
        None,
        description='Resource contents from after the change was made. If this resource was deleted in this change, this field will be missing.',
    )
    resourceBeforeChange: Optional[
        GoogleAnalyticsAdminV1betaChangeHistoryChangeChangeHistoryResource
    ] = Field(
        None,
        description='Resource contents from before the change was made. If this resource was created in this change, this field will be missing.',
    )


class GoogleAnalyticsAdminV1betaChangeHistoryEvent(BaseModel):
    actorType: Optional[ActorType] = Field(
        None, description='The type of actor that made this change.'
    )
    changeTime: Optional[str] = Field(None, description='Time when change was made.')
    changes: Optional[List[GoogleAnalyticsAdminV1betaChangeHistoryChange]] = Field(
        None,
        description='A list of changes made in this change history event that fit the filters specified in SearchChangeHistoryEventsRequest.',
    )
    changesFiltered: Optional[bool] = Field(
        None,
        description='If true, then the list of changes returned was filtered, and does not represent all changes that occurred in this event.',
    )
    id: Optional[str] = Field(
        None,
        description='ID of this change history event. This ID is unique across Google Analytics.',
    )
    userActorEmail: Optional[str] = Field(
        None,
        description='Email address of the Google account that made the change. This will be a valid email address if the actor field is set to USER, and empty otherwise. Google accounts that have been deleted will cause an error.',
    )


class GoogleAnalyticsAdminV1betaSearchChangeHistoryEventsResponse(BaseModel):
    changeHistoryEvents: Optional[
        List[GoogleAnalyticsAdminV1betaChangeHistoryEvent]
    ] = Field(None, description='Results that were accessible to the caller.')
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.',
    )


class GoogleAnalyticsAdminV1betaAccessFilterExpression(BaseModel):
    accessFilter: Optional[GoogleAnalyticsAdminV1betaAccessFilter] = Field(
        None,
        description="A primitive filter. In the same FilterExpression, all of the filter's field names need to be either all dimensions or all metrics.",
    )
    andGroup: Optional[GoogleAnalyticsAdminV1betaAccessFilterExpressionList] = Field(
        None,
        description='Each of the FilterExpressions in the and_group has an AND relationship.',
    )
    notExpression: Optional[GoogleAnalyticsAdminV1betaAccessFilterExpression] = Field(
        None, description='The FilterExpression is NOT of not_expression.'
    )
    orGroup: Optional[GoogleAnalyticsAdminV1betaAccessFilterExpressionList] = Field(
        None,
        description='Each of the FilterExpressions in the or_group has an OR relationship.',
    )


class GoogleAnalyticsAdminV1betaAccessFilterExpressionList(BaseModel):
    expressions: Optional[List[GoogleAnalyticsAdminV1betaAccessFilterExpression]] = (
        Field(None, description='A list of filter expressions.')
    )


class GoogleAnalyticsAdminV1betaRunAccessReportRequest(BaseModel):
    dateRanges: Optional[List[GoogleAnalyticsAdminV1betaAccessDateRange]] = Field(
        None,
        description='Date ranges of access records to read. If multiple date ranges are requested, each response row will contain a zero based date range index. If two date ranges overlap, the access records for the overlapping days is included in the response rows for both date ranges. Requests are allowed up to 2 date ranges.',
    )
    dimensionFilter: Optional[GoogleAnalyticsAdminV1betaAccessFilterExpression] = Field(
        None,
        description='Dimension filters let you restrict report response to specific dimension values which match the filter. For example, filtering on access records of a single user. To learn more, see [Fundamentals of Dimension Filters](https://developers.google.com/analytics/devguides/reporting/data/v1/basics#dimension_filters) for examples. Metrics cannot be used in this filter.',
    )
    dimensions: Optional[List[GoogleAnalyticsAdminV1betaAccessDimension]] = Field(
        None,
        description='The dimensions requested and displayed in the response. Requests are allowed up to 9 dimensions.',
    )
    limit: Optional[str] = Field(
        None,
        description="The number of rows to return. If unspecified, 10,000 rows are returned. The API returns a maximum of 100,000 rows per request, no matter how many you ask for. `limit` must be positive. The API may return fewer rows than the requested `limit`, if there aren't as many remaining rows as the `limit`. For instance, there are fewer than 300 possible values for the dimension `country`, so when reporting on only `country`, you can't get more than 300 rows, even if you set `limit` to a higher value. To learn more about this pagination parameter, see [Pagination](https://developers.google.com/analytics/devguides/reporting/data/v1/basics#pagination).",
    )
    metricFilter: Optional[GoogleAnalyticsAdminV1betaAccessFilterExpression] = Field(
        None,
        description="Metric filters allow you to restrict report response to specific metric values which match the filter. Metric filters are applied after aggregating the report's rows, similar to SQL having-clause. Dimensions cannot be used in this filter.",
    )
    metrics: Optional[List[GoogleAnalyticsAdminV1betaAccessMetric]] = Field(
        None,
        description='The metrics requested and displayed in the response. Requests are allowed up to 10 metrics.',
    )
    offset: Optional[str] = Field(
        None,
        description='The row count of the start row. The first row is counted as row 0. If offset is unspecified, it is treated as 0. If offset is zero, then this method will return the first page of results with `limit` entries. To learn more about this pagination parameter, see [Pagination](https://developers.google.com/analytics/devguides/reporting/data/v1/basics#pagination).',
    )
    orderBys: Optional[List[GoogleAnalyticsAdminV1betaAccessOrderBy]] = Field(
        None, description='Specifies how rows are ordered in the response.'
    )
    returnEntityQuota: Optional[bool] = Field(
        None,
        description="Toggles whether to return the current state of this Analytics Property's quota. Quota is returned in [AccessQuota](#AccessQuota). For account-level requests, this field must be false.",
    )
    timeZone: Optional[str] = Field(
        None,
        description='This request\'s time zone if specified. If unspecified, the property\'s time zone is used. The request\'s time zone is used to interpret the start & end dates of the report. Formatted as strings from the IANA Time Zone database (https://www.iana.org/time-zones); for example "America/New_York" or "Asia/Tokyo".',
    )


GoogleAnalyticsAdminV1betaAccessFilterExpression.model_rebuild()
